# Generated by Django 4.2.7 on 2023-11-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockinfo', '0002_alter_medicine_options_alter_pharmacy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='pharmacies',
            field=models.ManyToManyField(related_name='medicines', to='stockinfo.pharmacy', verbose_name='Аптеки'),
        ),
    ]
