# Generated by Django 4.2.7 on 2023-11-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockinfo', '0003_medicine_pharmacies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='pharmacies',
        ),
    ]
